// Generated by gencpp from file multi_map_nav/MultiMapNavResult.msg
// DO NOT EDIT!


#ifndef MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVRESULT_H
#define MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_map_nav
{
template <class ContainerAllocator>
struct MultiMapNavResult_
{
  typedef MultiMapNavResult_<ContainerAllocator> Type;

  MultiMapNavResult_()
    : status()  {
    }
  MultiMapNavResult_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> const> ConstPtr;

}; // struct MultiMapNavResult_

typedef ::multi_map_nav::MultiMapNavResult_<std::allocator<void> > MultiMapNavResult;

typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavResult > MultiMapNavResultPtr;
typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavResult const> MultiMapNavResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator1> & lhs, const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator1> & lhs, const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_map_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_map_nav/MultiMapNavResult";
  }

  static const char* value(const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"string status\n"
;
  }

  static const char* value(const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiMapNavResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_map_nav::MultiMapNavResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_map_nav::MultiMapNavResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVRESULT_H
