// Generated by gencpp from file multi_map_nav/MultiMapNavFeedback.msg
// DO NOT EDIT!


#ifndef MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVFEEDBACK_H
#define MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_map_nav
{
template <class ContainerAllocator>
struct MultiMapNavFeedback_
{
  typedef MultiMapNavFeedback_<ContainerAllocator> Type;

  MultiMapNavFeedback_()
    : success(false)  {
    }
  MultiMapNavFeedback_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MultiMapNavFeedback_

typedef ::multi_map_nav::MultiMapNavFeedback_<std::allocator<void> > MultiMapNavFeedback;

typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavFeedback > MultiMapNavFeedbackPtr;
typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavFeedback const> MultiMapNavFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator1> & lhs, const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator1> & lhs, const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_map_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_map_nav/MultiMapNavFeedback";
  }

  static const char* value(const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiMapNavFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_map_nav::MultiMapNavFeedback_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVFEEDBACK_H
