// Generated by gencpp from file multi_map_nav/MultiMapNavGoal.msg
// DO NOT EDIT!


#ifndef MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVGOAL_H
#define MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace multi_map_nav
{
template <class ContainerAllocator>
struct MultiMapNavGoal_
{
  typedef MultiMapNavGoal_<ContainerAllocator> Type;

  MultiMapNavGoal_()
    : target_map()
    , target_pose()  {
    }
  MultiMapNavGoal_(const ContainerAllocator& _alloc)
    : target_map(_alloc)
    , target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_map_type;
  _target_map_type target_map;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;





  typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MultiMapNavGoal_

typedef ::multi_map_nav::MultiMapNavGoal_<std::allocator<void> > MultiMapNavGoal;

typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavGoal > MultiMapNavGoalPtr;
typedef boost::shared_ptr< ::multi_map_nav::MultiMapNavGoal const> MultiMapNavGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator1> & lhs, const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_map == rhs.target_map &&
    lhs.target_pose == rhs.target_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator1> & lhs, const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_map_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e48063de98923cebf4a427d1072709d2";
  }

  static const char* value(const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe48063de98923cebULL;
  static const uint64_t static_value2 = 0xf4a427d1072709d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_map_nav/MultiMapNavGoal";
  }

  static const char* value(const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"string target_map\n"
"geometry_msgs/PoseStamped target_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_map);
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiMapNavGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_map_nav::MultiMapNavGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_map: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_map);
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MAP_NAV_MESSAGE_MULTIMAPNAVGOAL_H
