(cl:defpackage multi_map_nav-msg
  (:use )
  (:export
   "<MULTIMAPNAVACTION>"
   "MULTIMAPNAVACTION"
   "<MULTIMAPNAVACTIONFEEDBACK>"
   "MULTIMAPNAVACTIONFEEDBACK"
   "<MULTIMAPNAVACTIONGOAL>"
   "MULTIMAPNAVACTIONGOAL"
   "<MULTIMAPNAVACTIONRESULT>"
   "MULTIMAPNAVACTIONRESULT"
   "<MULTIMAPNAVFEEDBACK>"
   "MULTIMAPNAVFEEDBACK"
   "<MULTIMAPNAVGOAL>"
   "MULTIMAPNAVGOAL"
   "<MULTIMAPNAVRESULT>"
   "MULTIMAPNAVRESULT"
  ))

