; Auto-generated. Do not edit!


(cl:in-package multi_map_nav-msg)


;//! \htmlinclude MultiMapNavGoal.msg.html

(cl:defclass <MultiMapNavGoal> (roslisp-msg-protocol:ros-message)
  ((target_map
    :reader target_map
    :initarg :target_map
    :type cl:string
    :initform "")
   (target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass MultiMapNavGoal (<MultiMapNavGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MultiMapNavGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MultiMapNavGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_map_nav-msg:<MultiMapNavGoal> is deprecated: use multi_map_nav-msg:MultiMapNavGoal instead.")))

(cl:ensure-generic-function 'target_map-val :lambda-list '(m))
(cl:defmethod target_map-val ((m <MultiMapNavGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_map_nav-msg:target_map-val is deprecated.  Use multi_map_nav-msg:target_map instead.")
  (target_map m))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <MultiMapNavGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_map_nav-msg:target_pose-val is deprecated.  Use multi_map_nav-msg:target_pose instead.")
  (target_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MultiMapNavGoal>) ostream)
  "Serializes a message object of type '<MultiMapNavGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'target_map))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'target_map))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MultiMapNavGoal>) istream)
  "Deserializes a message object of type '<MultiMapNavGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target_map) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'target_map) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MultiMapNavGoal>)))
  "Returns string type for a message object of type '<MultiMapNavGoal>"
  "multi_map_nav/MultiMapNavGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MultiMapNavGoal)))
  "Returns string type for a message object of type 'MultiMapNavGoal"
  "multi_map_nav/MultiMapNavGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MultiMapNavGoal>)))
  "Returns md5sum for a message object of type '<MultiMapNavGoal>"
  "e48063de98923cebf4a427d1072709d2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MultiMapNavGoal)))
  "Returns md5sum for a message object of type 'MultiMapNavGoal"
  "e48063de98923cebf4a427d1072709d2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MultiMapNavGoal>)))
  "Returns full string definition for message of type '<MultiMapNavGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string target_map~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MultiMapNavGoal)))
  "Returns full string definition for message of type 'MultiMapNavGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string target_map~%geometry_msgs/PoseStamped target_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MultiMapNavGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'target_map))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MultiMapNavGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MultiMapNavGoal
    (cl:cons ':target_map (target_map msg))
    (cl:cons ':target_pose (target_pose msg))
))
