; Auto-generated. Do not edit!


(cl:in-package multi_map_nav-msg)


;//! \htmlinclude MultiMapNavFeedback.msg.html

(cl:defclass <MultiMapNavFeedback> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MultiMapNavFeedback (<MultiMapNavFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MultiMapNavFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MultiMapNavFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_map_nav-msg:<MultiMapNavFeedback> is deprecated: use multi_map_nav-msg:MultiMapNavFeedback instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MultiMapNavFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_map_nav-msg:success-val is deprecated.  Use multi_map_nav-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MultiMapNavFeedback>) ostream)
  "Serializes a message object of type '<MultiMapNavFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MultiMapNavFeedback>) istream)
  "Deserializes a message object of type '<MultiMapNavFeedback>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MultiMapNavFeedback>)))
  "Returns string type for a message object of type '<MultiMapNavFeedback>"
  "multi_map_nav/MultiMapNavFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MultiMapNavFeedback)))
  "Returns string type for a message object of type 'MultiMapNavFeedback"
  "multi_map_nav/MultiMapNavFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MultiMapNavFeedback>)))
  "Returns md5sum for a message object of type '<MultiMapNavFeedback>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MultiMapNavFeedback)))
  "Returns md5sum for a message object of type 'MultiMapNavFeedback"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MultiMapNavFeedback>)))
  "Returns full string definition for message of type '<MultiMapNavFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MultiMapNavFeedback)))
  "Returns full string definition for message of type 'MultiMapNavFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MultiMapNavFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MultiMapNavFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MultiMapNavFeedback
    (cl:cons ':success (success msg))
))
